-- MySQL Script generated by MySQL Workbench
-- mar 15 nov 2016 01:24:18 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema netflix
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema netflix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netflix` DEFAULT CHARACTER SET utf8 ;
USE `netflix` ;

-- -----------------------------------------------------
-- Table `netflix`.`TipoCuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`TipoCuenta` ;

CREATE TABLE IF NOT EXISTS `netflix`.`TipoCuenta` (
  `idTipoCuenta` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTipoCuenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Cuenta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Cuenta` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Cuenta` (
  `idCuenta` INT NOT NULL AUTO_INCREMENT,
  `idTipoCuenta` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `apellido` VARCHAR(100) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idCuenta`),
  INDEX `fk_Cuenta_TipoCuenta_idx` (`idTipoCuenta` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_Cuenta_TipoCuenta`
    FOREIGN KEY (`idTipoCuenta`)
    REFERENCES `netflix`.`TipoCuenta` (`idTipoCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `idCuenta` INT NOT NULL,
  `nombre` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_Cuenta1_idx` (`idCuenta` ASC),
  CONSTRAINT `fk_Usuario_Cuenta1`
    FOREIGN KEY (`idCuenta`)
    REFERENCES `netflix`.`Cuenta` (`idCuenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`ListaReproduccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`ListaReproduccion` ;

CREATE TABLE IF NOT EXISTS `netflix`.`ListaReproduccion` (
  `idListaReproduccion` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  PRIMARY KEY (`idListaReproduccion`),
  INDEX `fk_ListaReproduccion_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_ListaReproduccion_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `netflix`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Pelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Pelicula` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Pelicula` (
  `idPelicula` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `duracion` VARCHAR(45) NOT NULL,
  `fechaEstreno` DATE NOT NULL,
  `lenguaje` VARCHAR(45) NOT NULL,
  `puntuacion` DECIMAL NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `portada` VARCHAR(255) NOT NULL,
  `reparto` TEXT NOT NULL,
  `features` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idPelicula`),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Serie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Serie` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Serie` (
  `idSerie` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `puntuacion` DECIMAL NOT NULL,
  `fechaEstreno` DATE NOT NULL,
  `reparto` TEXT NOT NULL,
  `features` VARCHAR(45) NOT NULL,
  `lenguaje` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idSerie`),
  UNIQUE INDEX `titulo_UNIQUE` (`titulo` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Categoria` (
  `idCategoria` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Temporada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Temporada` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Temporada` (
  `idTemporada` INT NOT NULL AUTO_INCREMENT,
  `idSerie` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTemporada`),
  INDEX `fk_Temporada_Serie1_idx` (`idSerie` ASC),
  CONSTRAINT `fk_Temporada_Serie1`
    FOREIGN KEY (`idSerie`)
    REFERENCES `netflix`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`PeliculaCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`PeliculaCategoria` ;

CREATE TABLE IF NOT EXISTS `netflix`.`PeliculaCategoria` (
  `idPelicula` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idPelicula`, `idCategoria`),
  INDEX `fk_Pelicula_has_Categoria_Categoria1_idx` (`idCategoria` ASC),
  INDEX `fk_Pelicula_has_Categoria_Pelicula1_idx` (`idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Categoria_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `netflix`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Categoria_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `netflix`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`PeliculaCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`PeliculaCategoria` ;

CREATE TABLE IF NOT EXISTS `netflix`.`PeliculaCategoria` (
  `idPelicula` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idPelicula`, `idCategoria`),
  INDEX `fk_Pelicula_has_Categoria_Categoria1_idx` (`idCategoria` ASC),
  INDEX `fk_Pelicula_has_Categoria_Pelicula1_idx` (`idPelicula` ASC),
  CONSTRAINT `fk_Pelicula_has_Categoria_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `netflix`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelicula_has_Categoria_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `netflix`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`SerieCategoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`SerieCategoria` ;

CREATE TABLE IF NOT EXISTS `netflix`.`SerieCategoria` (
  `idSerie` INT NOT NULL,
  `idCategoria` INT NOT NULL,
  PRIMARY KEY (`idCategoria`, `idSerie`),
  INDEX `fk_Serie_has_Categoria_Categoria1_idx` (`idCategoria` ASC),
  INDEX `fk_Serie_has_Categoria_Serie1_idx` (`idSerie` ASC),
  CONSTRAINT `fk_Serie_has_Categoria_Serie1`
    FOREIGN KEY (`idSerie`)
    REFERENCES `netflix`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Serie_has_Categoria_Categoria1`
    FOREIGN KEY (`idCategoria`)
    REFERENCES `netflix`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`UsuarioPelicula`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`UsuarioPelicula` ;

CREATE TABLE IF NOT EXISTS `netflix`.`UsuarioPelicula` (
  `idUsuario` INT NOT NULL,
  `idPelicula` INT NOT NULL,
  `puntuacion` DECIMAL NULL,
  `reseña` TEXT NULL,
  `minActual` INT NULL,
  PRIMARY KEY (`idUsuario`, `idPelicula`),
  INDEX `fk_Usuario_has_Pelicula_Pelicula1_idx` (`idPelicula` ASC),
  INDEX `fk_Usuario_has_Pelicula_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Pelicula_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `netflix`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Pelicula_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `netflix`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`UsuarioSerie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`UsuarioSerie` ;

CREATE TABLE IF NOT EXISTS `netflix`.`UsuarioSerie` (
  `idUsuario` INT NOT NULL,
  `idSerie` INT NOT NULL,
  `puntuacion` DECIMAL NULL,
  `reseña` TEXT NULL,
  `minActual` INT NULL,
  PRIMARY KEY (`idSerie`, `idUsuario`),
  INDEX `fk_Usuario_has_Serie_Serie1_idx` (`idSerie` ASC),
  INDEX `fk_Usuario_has_Serie_Usuario1_idx` (`idUsuario` ASC),
  CONSTRAINT `fk_Usuario_has_Serie_Usuario1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `netflix`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Serie_Serie1`
    FOREIGN KEY (`idSerie`)
    REFERENCES `netflix`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`Capitulo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`Capitulo` ;

CREATE TABLE IF NOT EXISTS `netflix`.`Capitulo` (
  `idCapitulo` INT NOT NULL AUTO_INCREMENT,
  `idTemporada` INT NOT NULL,
  `numeroCapitulo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `duracion` INT NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `portada` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCapitulo`),
  INDEX `fk_Capitulo_Temporada1_idx` (`idTemporada` ASC),
  CONSTRAINT `fk_Capitulo_Temporada1`
    FOREIGN KEY (`idTemporada`)
    REFERENCES `netflix`.`Temporada` (`idTemporada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `netflix`.`ListaDetalle`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `netflix`.`ListaDetalle` ;

CREATE TABLE IF NOT EXISTS `netflix`.`ListaDetalle` (
  `idListaDetalle` INT NOT NULL AUTO_INCREMENT,
  `idListaReproduccion` INT NOT NULL,
  `idPelicula` INT NULL,
  `idSerie` INT NULL,
  INDEX `fk_ListaDetalle_ListaReproduccion1_idx` (`idListaReproduccion` ASC),
  INDEX `fk_ListaDetalle_Pelicula1_idx` (`idPelicula` ASC),
  INDEX `fk_ListaDetalle_Serie1_idx` (`idSerie` ASC),
  PRIMARY KEY (`idListaDetalle`),
  CONSTRAINT `fk_ListaDetalle_ListaReproduccion1`
    FOREIGN KEY (`idListaReproduccion`)
    REFERENCES `netflix`.`ListaReproduccion` (`idListaReproduccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaDetalle_Pelicula1`
    FOREIGN KEY (`idPelicula`)
    REFERENCES `netflix`.`Pelicula` (`idPelicula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ListaDetalle_Serie1`
    FOREIGN KEY (`idSerie`)
    REFERENCES `netflix`.`Serie` (`idSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
